baseurl = "/"
languageCode = "en-us"
title = "Musings"
theme = "nofancy"

[params]
    images = ["https://musings.ackushiw/images/ackushiw.jpg"]
    highlight="Assign a syntax highlight style"
    description = "Random musings about random things"

[author]
    copyright = "Copyright (c) 2008 - 2017, Alexander Kushi-Willis; all rights reserved."
    name = "Alexander Kushi-Willis"
    website = "ackushiw.com"
    github = "ackushiw"
    linkedin = "alexander-kushi-willis-6a620527"
    facebook = "ackushiw"
    gaID = "UA-25355223-4"
    twitter = "ackushiw"
