baseurl = "/"
languageCode = "en-us"
title = "Musings"
theme = "nofancy"

#if not set copyright, default copyright template will be applied
copyright = "Copyright (c) 2008 - 2014, Alexander Kushi-Willis; all rights reserved."

[params]
    highlight="Assign a syntax highlight style"

[author]
    name = "Alexander Kushi-Willis"
    website = "ackushiw.com"
    github = "ackushiw"
    linkedin = "alexander-kushi-willis-6a620527"
    facebook = "ackushiw"
    gaID = "UA-25355223-4"
    twitter = "ackushiw"
